from tests.test_core import (
    test_classifier, test_expanded_baby_product_classifier,
    test_baby_only_classifier_rejects_adult_and_general_products,
    test_verified_product_image_extraction,
    test_image_enrichment_verifies_exact_barcode,
    test_product_photo_is_rejected_when_barcode_does_not_match,
    test_expanded_product_package_quantities, test_dimensions, test_quantities,
    test_xml_price_and_store, test_xml_imports_expanded_product_categories,
    test_catalog_collects_products_from_every_supermarket,
    test_zero_source_numbers_are_safely_sanitized,
    test_multi_buy_promotion_terms, test_ksp_official_product_parser,
    test_ksp_print_page_fallback_parser,
    test_ksp_json_api_barcode_search_parser,
    test_ksp_json_api_detail_finds_barcode_in_specification,
    test_ksp_relay_routes_and_authenticates_request,
    test_superpharm_promo_filename_and_merge,
    test_superpharm_online_product_and_promo_parser,
    test_superpharm_online_multi_buy_parser,
    test_superpharm_category_product_url_extraction,
    test_strict_source_outcome_is_not_false_success,
    test_cheapersal_price_fallback_normalizes_matching_chain,
)
from tests.test_mvp_v046_contract import (
    test_v046_frontend_enforces_trustworthy_basket_rules,
    test_v046_sql_view_has_explicit_api_grant_and_invoker_security,
)
from tests.test_v047_contract import (
    test_v047_family_choice_and_visible_names,
    test_v047_formula_requires_a_brand_without_automatic_substitution,
    test_v047_inventory_preserves_purchase_history,
    test_v047_partial_baskets_and_savings_are_visible,
    test_v047_sql_is_secure_and_non_destructive,
)

for fn in (
    test_classifier, test_expanded_baby_product_classifier,
    test_baby_only_classifier_rejects_adult_and_general_products,
    test_verified_product_image_extraction,
    test_image_enrichment_verifies_exact_barcode,
    test_product_photo_is_rejected_when_barcode_does_not_match,
    test_expanded_product_package_quantities, test_dimensions, test_quantities,
    test_xml_price_and_store, test_xml_imports_expanded_product_categories,
    test_catalog_collects_products_from_every_supermarket,
    test_zero_source_numbers_are_safely_sanitized,
    test_multi_buy_promotion_terms, test_ksp_official_product_parser,
    test_ksp_print_page_fallback_parser,
    test_ksp_json_api_barcode_search_parser,
    test_ksp_json_api_detail_finds_barcode_in_specification,
    test_ksp_relay_routes_and_authenticates_request,
    test_superpharm_promo_filename_and_merge,
    test_superpharm_online_product_and_promo_parser,
    test_superpharm_online_multi_buy_parser,
    test_superpharm_category_product_url_extraction,
    test_strict_source_outcome_is_not_false_success,
    test_cheapersal_price_fallback_normalizes_matching_chain,
    test_v046_frontend_enforces_trustworthy_basket_rules,
    test_v046_sql_view_has_explicit_api_grant_and_invoker_security,
    test_v047_inventory_preserves_purchase_history,
    test_v047_formula_requires_a_brand_without_automatic_substitution,
    test_v047_partial_baskets_and_savings_are_visible,
    test_v047_family_choice_and_visible_names,
    test_v047_sql_is_secure_and_non_destructive,
):
    fn()
    print(f"✅ {fn.__name__}")
print("✅ All local parser/classifier self-tests passed.")
